version: 2.1

orbs:
  python-build: ffy00/python-build@0.0.1

jobs:
  build:
    docker:
      - image: circleci/python:3.8
    steps:
      - checkout
      - run: pip install flit_core  # https://github.com/FFY00/python-build/issues/98
      - python-build/build
